### ISSUE TITLE
[Arcs] Clarify cartel guild card discard prelude ability 

### ISSUE THREAD

**Issue by fallspectrum** [LederCards/cards#67] opened 2024-11-07 19:00 UTC
Can you discard cartel cards during prelude even if there are no associated resources to steal from other players?  Would be helpful to clarify this for both cartel cards.

**Comment by turmoilbyrd** [comment] 2024-11-07 20:09
Duplicate of https://github.com/LederCards/cards/issues/31

**Comment by fallspectrum** [comment] 2024-11-08 20:34
Will leave this open as an indirect means of bumping the relevance of #31 until someone else closes it.

**Comment by jdyearsley** [comment] 2024-12-19 19:08
Will answer #31

**Closed by jdyearsley** 2024-12-19 19:08 UTC
